frontend:
  image: dheerajkr7866/3-tier-app-with-terraform:frontend5
  port: 80

backend:
  image: dheerajkr7866/3-tier-app-with-terraform:backend
  port: 5000

mongo:
  image: mongo:4.4
  port: 27017

env:
  BACKEND_ENV:
    - name: MONGO_URL
      value: "mongodb://mongo:27017/simpleapp"
    - name: NODE_ENV
      value: "development"

  FRONTEND_ENV:
    - name: REACT_APP_API_URL
      value: "/api"

replicaCount: 1


ingress:
  enabled: true
  className: nginx
  hosts:
    - host: frontend.local
      serviceName: frontend
      servicePort: 80
    - host: backend.local
      serviceName: backend
      servicePort: 5000
  tls: false
